name: CI

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/frontend.yml'
      - 'blog.luciano.goncalves.dev/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: npm install
      working-directory: ./blog.luciano.goncalves.dev
    - name: Run a multi-line script
      run: |
        npm run build-prod
        cd dist/lgblog
        pwd
      working-directory: ./blog.luciano.goncalves.dev
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: './blog.luciano.goncalves.dev/dist/lgblog'
        
  deploy:
    runs-on: [ubuntu-latest]
    env:
      PROJECT_ID: lucianogoncalves-blog
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
