name: CI

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/frontend.yml'
      - 'blog.luciano.goncalves.dev/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT: lucianogoncalves-blog
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        npm install
        npm run build-prod
        ls
      working-directory: ./blog.luciano.goncalves.dev
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: 'blog.luciano.goncalves.dev/dist/lgblog/**'
