name: CI

on:
  push:
    branches: 
      - '*'
    paths:
      - 'blog.luciano.goncalves.dev/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        cd blog.luciano.goncalves.dev
        npm install
        npm run build-prod
